/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/budget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the list of the user's budgets */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description everything is fine */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["budget"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a new budget */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description the budget name */
                        name: string;
                    };
                };
            };
            responses: {
                /** @description Successfully created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["budget"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget/{budgetId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** get a budget's month summary for the current month */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    budgetId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The budgets monthly summary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["budgetMonth"];
                    };
                };
            };
        };
        /** Update a budget */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    budgetId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description the new budget name */
                        name: string;
                    };
                };
            };
            responses: {
                /** @description Successfully updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["budget"];
                    };
                };
            };
        };
        post?: never;
        /** Delete a budget */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    budgetId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget/{budgetId}/{month}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** get a budget's month summary for the current month */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                    /** @description the monthly budget to pull */
                    month: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["budgetMonth"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget/{budgetId}/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the lisst of accounts in a budget with balance information */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["accountSummaryDetail"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a new account in a budget */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description The name of the new account */
                        name: string;
                    };
                };
            };
            responses: {
                /** @description Successfully created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["account"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget/{budgetId}/account/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an account's balance summary and its transactions */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                    /** @description the account id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The account summary and its transactions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["accountDetail"];
                    };
                };
            };
        };
        /** Update an account */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                    /** @description the account id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description The new account name */
                        name: string;
                    };
                };
            };
            responses: {
                /** @description Successfully updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["account"];
                    };
                };
            };
        };
        post?: never;
        /** Delete an account */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                    /** @description the account id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget/{budgetId}/account/{id}/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import transactions into an account from a bank statement file */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                    /** @description the account id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /**
                         * Format: binary
                         * @description The bank statement file to import
                         */
                        statement: string;
                    };
                };
            };
            responses: {
                /** @description The number of transactions imported */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget/{budgetId}/account/{id}/reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reconcile an account against a statement balance */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                    /** @description the account id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description Reconcile all transactions up to and including this date (RFC3339) */
                        date: string;
                        /** @description The statement balance as of the date (in cents) */
                        balance: number;
                    };
                };
            };
            responses: {
                /** @description Successfully reconciled */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget/{budgetId}/account/{accountId}/transaction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new transaction in an account */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                    /** @description the account id */
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description The payee the transaction is with */
                        payeeId: number;
                        /** @description The transaction date (RFC3339) */
                        date: string;
                        /** @description The total outflow of the transaction */
                        outflow: number;
                        /** @description The total inflow of the transaction */
                        inflow: number;
                        /** @description A note on the transaction */
                        note?: string;
                    };
                };
            };
            responses: {
                /** @description Successfully created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["transaction"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget/{budgetId}/account/{accountId}/transaction/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a transaction */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                    /** @description the account id */
                    accountId: string;
                    /** @description the transaction id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description The payee the transaction is with */
                        payeeId: number;
                        /** @description The transaction date (RFC3339) */
                        date: string;
                        /** @description The total outflow of the transaction */
                        outflow: number;
                        /** @description The total inflow of the transaction */
                        inflow: number;
                        /** @description A note on the transaction */
                        note?: string;
                    };
                };
            };
            responses: {
                /** @description Successfully updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["transaction"];
                    };
                };
            };
        };
        post?: never;
        /** Delete a transaction */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                    /** @description the account id */
                    accountId: string;
                    /** @description the transaction id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget/{budgetId}/account/{accountId}/transaction/{trxId}/line": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new line on a transaction */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                    /** @description the account id */
                    accountId: string;
                    /** @description the transaction id */
                    trxId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description The destination account id (for transfer lines) */
                        destAccountId?: number;
                        /** @description The category id (for spend lines) */
                        categoryId?: number;
                        /** @description Whether this is an income line */
                        income?: boolean;
                        /** @description The expense share id (for reimbursement lines) */
                        expenseShareId?: number;
                        /** @description The outflow of this line */
                        outflow: number;
                        /** @description The inflow of this line */
                        inflow: number;
                    };
                };
            };
            responses: {
                /** @description Successfully created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["trxLine"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget/{budgetId}/account/{accountId}/transaction/{trxId}/line/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a line on a transaction */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                    /** @description the account id */
                    accountId: string;
                    /** @description the transaction id */
                    trxId: string;
                    /** @description the line id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description The destination account id (for transfer lines) */
                        destAccountId?: number;
                        /** @description The category id (for spend lines) */
                        categoryId?: number;
                        /** @description Whether this is an income line */
                        income?: boolean;
                        /** @description The expense share id (for reimbursement lines) */
                        expenseShareId?: number;
                        /** @description The outflow of this line */
                        outflow: number;
                        /** @description The inflow of this line */
                        inflow: number;
                    };
                };
            };
            responses: {
                /** @description Successfully updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["trxLine"];
                    };
                };
            };
        };
        post?: never;
        /** Delete a line on a transaction */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                    /** @description the account id */
                    accountId: string;
                    /** @description the transaction id */
                    trxId: string;
                    /** @description the line id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget/{budgetId}/category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the list of categories in a budget */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The list of categories */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["category"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a new category in a budget */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description The name of the new category */
                        name: string;
                        /** @description The id of the category group this category belongs to (if any) */
                        categoryGroupId?: number;
                    };
                };
            };
            responses: {
                /** @description Successfully created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["category"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget/{budgetId}/category/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a category */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                    /** @description the category id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description The new category name */
                        name: string;
                        /** @description The id of the category group this category belongs to (if any) */
                        categoryGroupId?: number;
                    };
                };
            };
            responses: {
                /** @description Successfully updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["category"];
                    };
                };
            };
        };
        post?: never;
        /** Delete a category */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                    /** @description the category id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget/{budgetId}/category/{id}/allocation/{month}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set the allocation amount for a category in a given month */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                    /** @description the category id */
                    id: string;
                    /** @description the month to allocate for (YYYY-MM) */
                    month: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description The amount to allocate to this category for the month */
                        amount: number;
                    };
                };
            };
            responses: {
                /** @description Successfully allocated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["allocation"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget/{budgetId}/category/{categoryId}/goal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the goal for a category in a budget */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                    /** @description the category id */
                    categoryId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The goal for the category */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["goal"];
                    };
                };
            };
        };
        /** Update the goal for a category in a budget */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                    /** @description the category id */
                    categoryId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /**
                         * @description The type of goal
                         * @enum {string}
                         */
                        type: "monthly" | "save" | "refill";
                        /** @description The month the goal starts (YYYY-MM) */
                        startMonth: string;
                        /** @description The month the goal ends (exclusive, required for save goals) */
                        endMonth?: string;
                        /** @description The goals amount value (meaning varies by type) */
                        amount: number;
                    };
                };
            };
            responses: {
                /** @description Successfully updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["goal"];
                    };
                };
            };
        };
        /** Create a new goal for a category in a budget */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                    /** @description the category id */
                    categoryId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /**
                         * @description The type of goal
                         * @enum {string}
                         */
                        type: "monthly" | "save" | "refill";
                        /** @description The month the goal starts (YYYY-MM) */
                        startMonth: string;
                        /** @description The month the goal ends (exclusive, required for save goals) */
                        endMonth?: string;
                        /** @description The goals amount value (meaning varies by type) */
                        amount: number;
                    };
                };
            };
            responses: {
                /** @description Successfully created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["goal"];
                    };
                };
            };
        };
        /** Delete the goal for a category in a budget */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                    /** @description the category id */
                    categoryId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget/{budgetId}/category-group": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the list of category groups in a budget */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The list of category groups */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["categoryGroup"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a new category group in a budget */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description The name of the new category group */
                        name: string;
                    };
                };
            };
            responses: {
                /** @description Successfully created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["categoryGroup"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget/{budgetId}/category-group/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a category group */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                    /** @description the category group id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description The new category group name */
                        name: string;
                    };
                };
            };
            responses: {
                /** @description Successfully updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["categoryGroup"];
                    };
                };
            };
        };
        post?: never;
        /** Delete a category group */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                    /** @description the category group id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget/{budgetId}/payee": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the list of payees in a budget */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The list of payees */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["payee"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a new payee in a budget */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description The name of the new payee */
                        name: string;
                    };
                };
            };
            responses: {
                /** @description Successfully created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["payee"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget/{budgetId}/payee/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a payee */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                    /** @description the payee id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description The new payee name */
                        name: string;
                    };
                };
            };
            responses: {
                /** @description Successfully updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["payee"];
                    };
                };
            };
        };
        post?: never;
        /** Delete a payee */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                    /** @description the payee id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget/{budgetId}/payee/{payeeId}/default-line": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the list of default lines for a payee in a budget */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                    /** @description the payee id */
                    payeeId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The list of default lines for the payee */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["payeeDefaultLine"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a new default line for a payee in a budget */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                    /** @description the payee id */
                    payeeId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description The destination account id (for transfer lines) */
                        destAccountId?: number;
                        /** @description The category id (for spend lines) */
                        categoryId?: number;
                        /** @description Whether this is an income line */
                        income?: boolean;
                        /** @description The expense share id (for reimbursement lines) */
                        expenseShareId?: number;
                        /** @description The percent of the transaction this line accounts for */
                        percent: number;
                    };
                };
            };
            responses: {
                /** @description Successfully created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["payeeDefaultLine"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget/{budgetId}/payee/{payeeId}/default-line/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a default line for a payee in a budget */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                    /** @description the payee id */
                    payeeId: string;
                    /** @description the default line id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description The destination account id (for transfer lines) */
                        destAccountId?: number;
                        /** @description The category id (for spend lines) */
                        categoryId?: number;
                        /** @description Whether this is an income line */
                        income?: boolean;
                        /** @description The expense share id (for reimbursement lines) */
                        expenseShareId?: number;
                        /** @description The percent of the transaction this line accounts for */
                        percent: number;
                    };
                };
            };
            responses: {
                /** @description Successfully updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["payeeDefaultLine"];
                    };
                };
            };
        };
        post?: never;
        /** Delete a default line for a payee in a budget */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                    /** @description the payee id */
                    payeeId: string;
                    /** @description the default line id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget/{budgetId}/expense-share": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the list of expense share memberships in a budget */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The list of expense share memberships */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["expenseShareMembership"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a new expense share with this budget as the first member */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description The global default name (immutable, defaults to name) */
                        defaultName?: string;
                        /** @description How this expense share is displayed for this budget */
                        name: string;
                        /** @description How this budget is displayed to other members */
                        displayName: string;
                    };
                };
            };
            responses: {
                /** @description Successfully created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["expenseShareMembership"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget/{budgetId}/expense-share/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join an expense share via an invite code */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description The invite code minted by an existing member */
                        code: string;
                        /** @description How this expense share is displayed for this budget */
                        name: string;
                        /** @description How this budget is displayed to other members */
                        displayName: string;
                    };
                };
            };
            responses: {
                /** @description Successfully joined */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["expenseShareMembership"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget/{budgetId}/expense-share/{shareId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an expense share with members, shared transactions and splits */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                    /** @description the expense share id */
                    shareId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The expense share detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["expenseShareDetail"];
                    };
                };
            };
        };
        /** Rename an expense share membership (local name and display name) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                    /** @description the expense share id */
                    shareId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description How this expense share is displayed for this budget */
                        name?: string;
                        /** @description How this budget is displayed to other members */
                        displayName?: string;
                    };
                };
            };
            responses: {
                /** @description Successfully updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["expenseShareMembership"];
                    };
                };
            };
        };
        post?: never;
        /** Leave an expense share (auto-deletes the share when the last member leaves) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                    /** @description the expense share id */
                    shareId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully left */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget/{budgetId}/expense-share/{shareId}/codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mint a new invite code for an expense share (server-generated, server-decided expiry) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                    /** @description the expense share id */
                    shareId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully minted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["expenseShareCode"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget/{budgetId}/expense-share/{shareId}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish a transaction to an expense share (requested sums the source expense-share lines, snapshot taken once) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                    /** @description the expense share id */
                    shareId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description The source transaction to publish */
                        trxId: number;
                    };
                };
            };
            responses: {
                /** @description Successfully published */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["sharedTransaction"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget/{budgetId}/expense-share/{shareId}/transactions/{sharedTrxId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a shared transaction with all splits (only the caller's own split lines included) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                    /** @description the expense share id */
                    shareId: string;
                    /** @description the shared transaction id */
                    sharedTrxId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The shared transaction */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["sharedTransaction"];
                    };
                };
            };
        };
        /** Re-snapshot a shared transaction from its source (re-sums requested, re-copies totals) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                    /** @description the expense share id */
                    shareId: string;
                    /** @description the shared transaction id */
                    sharedTrxId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description The source transaction to re-snapshot from (defaults to the linked source) */
                        trxId?: number;
                    };
                };
            };
            responses: {
                /** @description Successfully re-snapshotted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["sharedTransaction"];
                    };
                };
            };
        };
        post?: never;
        /** Unpublish a shared transaction for all members */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                    /** @description the expense share id */
                    shareId: string;
                    /** @description the shared transaction id */
                    sharedTrxId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully unpublished */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget/{budgetId}/expense-share/{shareId}/transactions/{sharedTrxId}/splits/{memberBudgetId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set any member's split portion (open-edit, 0/0 means not participating, sum mismatch is a warning) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                    /** @description the expense share id */
                    shareId: string;
                    /** @description the shared transaction id */
                    sharedTrxId: string;
                    /** @description the member budget whose split is set */
                    memberBudgetId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description The member's outflow portion */
                        splitOutflow: number;
                        /** @description The member's inflow portion */
                        splitInflow: number;
                    };
                };
            };
            responses: {
                /** @description Successfully set */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["shareSplit"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget/{budgetId}/expense-share/{shareId}/transactions/{sharedTrxId}/splits/{memberBudgetId}/lines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Categorize my split of a shared transaction (private to the owning budget) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                    /** @description the expense share id */
                    shareId: string;
                    /** @description the shared transaction id */
                    sharedTrxId: string;
                    /** @description the member budget whose split is categorized (must match the path budget) */
                    memberBudgetId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description The destination account id (for transfer lines) */
                        destAccountId?: number;
                        /** @description The category id (for spend lines) */
                        categoryId?: number;
                        /** @description The outflow of this line */
                        outflow: number;
                        /** @description The inflow of this line */
                        inflow: number;
                    };
                };
            };
            responses: {
                /** @description Successfully created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["splitLine"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget/{budgetId}/expense-share/{shareId}/transactions/{sharedTrxId}/splits/{memberBudgetId}/lines/{lineId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update my split line (private to the owning budget) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                    /** @description the expense share id */
                    shareId: string;
                    /** @description the shared transaction id */
                    sharedTrxId: string;
                    /** @description the member budget whose split is categorized (must match the path budget) */
                    memberBudgetId: string;
                    /** @description the split line id */
                    lineId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description The destination account id (for transfer lines) */
                        destAccountId?: number;
                        /** @description The category id (for spend lines) */
                        categoryId?: number;
                        /** @description The outflow of this line */
                        outflow: number;
                        /** @description The inflow of this line */
                        inflow: number;
                    };
                };
            };
            responses: {
                /** @description Successfully updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["splitLine"];
                    };
                };
            };
        };
        post?: never;
        /** Delete my split line (private to the owning budget) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the budget id */
                    budgetId: string;
                    /** @description the expense share id */
                    shareId: string;
                    /** @description the shared transaction id */
                    sharedTrxId: string;
                    /** @description the member budget whose split is categorized (must match the path budget) */
                    memberBudgetId: string;
                    /** @description the split line id */
                    lineId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        budget: {
            /** @description The budget id */
            id: number;
            /** @description The budget name */
            name: string;
        };
        budgetMonth: {
            /** @description The month the budget is for (first day) */
            month: string;
            summary: components["schemas"]["budgetMonthSummary"];
            /** @description The list of all the categories and their values for the month */
            categories: components["schemas"]["budgetMonthCategory"][];
        };
        budgetMonthCategory: {
            categoryId: number;
            categoryName: string;
            categoryGroupName?: string;
            /** @description The amount of money allocated to this category this month */
            allocated: number;
            /** @description The amount of money spent in this category this month */
            spent: number;
            /** @description The amount of money available to spen in this category (to date allocations - spend) */
            available: number;
            goal?: components["schemas"]["budgetMonthGoal"];
        };
        budgetMonthSummary: {
            /** @description The amount of money that is available to assign (net worth - already assigned to date) */
            readyToAssign: number;
            /** @description The total income for the month */
            income: number;
            /** @description The total allocated for the month */
            allocated: number;
            /** @description The total spent for the month */
            spent: number;
            /** @description The absolute value of the uncategorize transactions */
            uncategorized: number;
        };
        budgetMonthGoal: {
            /**
             * @description The type of goal this is
             * @enum {string}
             */
            type: "monthly" | "save" | "refill";
            /** @description The month the goal started */
            startMonth: string;
            /** @description The month the goal ends (exclusive) */
            endMonth?: string;
            /** @description The goals amount value (meaning varies by type) */
            amount: number;
            /** @description The total amount allocated to this goal to date (previous months only) */
            allocated: number;
            /** @description The amount needed to allocated this month to stay on track */
            amountForMonth: number;
            /** @description The difference between the allocated amount and the amountForMonth */
            gap: number;
        };
        account: {
            /** @description The account id */
            id: number;
            /** @description The account name */
            name: string;
        };
        accountDetail: {
            summary: components["schemas"]["accountSummaryDetail"];
            /** @description The account's transactions, each with its nested transaction lines */
            transactions: components["schemas"]["accountTransaction"][];
        };
        accountSummaryDetail: {
            id: number;
            name: string;
            balance: number;
            reconciledBalance: number;
        };
        accountTransaction: {
            id: number;
            /** @description The account the funds were transferred from (present only on mirror transfer rows) */
            sourceAccountId?: number;
            /** @description The name of the account the funds were transferred from (present only on mirror transfer rows) */
            sourceAccountName?: string;
            date: string;
            payeeId: number;
            payeeName: string;
            /** @description The total outflow of the transaction */
            outflow: number;
            /** @description The total inflow of the transaction */
            inflow: number;
            note: string;
            reconciled: boolean;
            /** @description The transaction's lines (category allocations and transfers) */
            transactionLines: components["schemas"]["accountTransactionLine"][];
        };
        /**
         * @description a transaction line, can be one of a transfer to a destination account,
         *     income, a categorization, or a reimbursement to an expense share.
         */
        accountTransactionLine: {
            lineId: number;
            destAccountId?: number;
            destAccountName?: string;
            categoryId?: number;
            categoryName?: string;
            /** @description The expense share id (present on reimbursement lines) */
            expenseShareId?: number;
            income: boolean;
            outflow: number;
            inflow: number;
        };
        category: {
            /** @description The category id */
            id: number;
            /** @description The category name */
            name: string;
            /** @description The id of the category group this category belongs to (if any) */
            categoryGroupId?: number;
        };
        categoryGroup: {
            /** @description The category group id */
            id: number;
            /** @description The category group name */
            name: string;
        };
        allocation: {
            /** @description The allocation id */
            id: number;
            /** @description The category the allocation is for */
            categoryId: number;
            /** @description The month the allocation is for (first day) */
            month: string;
            /** @description The amount allocated to the category for the month */
            amount: number;
        };
        goal: {
            /** @description The goal id */
            id: number;
            /** @description The category the goal is for */
            categoryId: number;
            /**
             * @description The type of goal
             * @enum {string}
             */
            type: "monthly" | "save" | "refill";
            /** @description The month the goal started (first day) */
            startMonth: string;
            /** @description The month the goal ends (exclusive) */
            endMonth?: string;
            /** @description The goals amount value (meaning varies by type) */
            amount: number;
        };
        payee: {
            /** @description The payee id */
            id: number;
            /** @description The payee name */
            name: string;
        };
        payeeDefaultLine: {
            /** @description The default line id */
            id: number;
            /** @description The payee the default line is for */
            payeeId: number;
            /** @description The destination account id (present on transfer lines) */
            destAccountId?: number;
            /** @description The destination account name (present on list responses) */
            destAccountName?: string;
            /** @description The category id (present on spend lines) */
            categoryId?: number;
            /** @description The category name (present on list responses) */
            categoryName?: string;
            /** @description Whether this is an income line */
            income: boolean;
            /** @description The expense share id (present on reimbursement lines) */
            expenseShareId?: number;
            /** @description The percent of the transaction this line accounts for */
            percent: number;
        };
        transaction: {
            /** @description The transaction id */
            id: number;
            /** @description The account the transaction is in */
            accountId: number;
            /** @description The payee the transaction is with */
            payeeId: number;
            /** @description The transaction date (RFC3339) */
            date: string;
            /** @description The total outflow of the transaction */
            outflow: number;
            /** @description The total inflow of the transaction */
            inflow: number;
            /** @description A note on the transaction */
            note: string;
        };
        trxLine: {
            /** @description The line id */
            id: number;
            /** @description The transaction the line is on */
            trxId: number;
            /** @description The destination account id (present on transfer lines) */
            destAccountId?: number;
            /** @description The category id (present on spend lines) */
            categoryId?: number;
            /** @description Whether this is an income line */
            income: boolean;
            /** @description The expense share id (present on reimbursement lines) */
            expenseShareId?: number;
            /** @description The outflow of this line */
            outflow: number;
            /** @description The inflow of this line */
            inflow: number;
        };
        expenseShareMembership: {
            /** @description The membership id */
            id: number;
            /** @description The global expense share id */
            expenseShareId: number;
            /** @description The member budget id */
            budgetId: number;
            /** @description How this expense share is displayed for this budget */
            name: string;
            /** @description How this budget is displayed to other members */
            displayName: string;
        };
        expenseShareDetail: {
            membership: components["schemas"]["expenseShareMembership"];
            summary: components["schemas"]["expenseShareSummary"];
            /** @description All budgets in the expense share */
            members: components["schemas"]["shareMember"][];
            /** @description Published snapshot transactions with splits (only the caller's own split lines included) */
            sharedTransactions: components["schemas"]["sharedTransaction"][];
        };
        expenseShareSummary: {
            /** @description Caller net (requested outflow minus inflow where I source, minus my splits elsewhere; positive means others owe me) */
            balance: number;
            /** @description Pairwise nets with each other active member (self excluded, zero-activity omitted) */
            memberBalances: components["schemas"]["expenseShareMemberBalance"][];
        };
        expenseShareMemberBalance: {
            /** @description The other member budget id */
            budgetId: number;
            /** @description How this member is displayed to other members */
            displayName: string;
            /** @description Net with this member (their splits on my publishes minus my splits on theirs, outflow minus inflow; positive means they owe me) */
            balance: number;
        };
        shareMember: {
            /** @description The member budget id */
            budgetId: number;
            /** @description How this member is displayed to other members */
            displayName: string;
        };
        expenseShareCode: {
            /** @description The invite code (server-generated, shown once) */
            code: string;
            /** @description When the code expires (RFC3339, server-decided) */
            expires: string;
        };
        sharedTransaction: {
            /** @description The shared transaction id */
            id: number;
            /** @description The budget ID of the member who published the transaction */
            sourceBudget: number;
            /** @description The expense share it was published to */
            expenseShareId: number;
            /** @description Snapshot of the source payee name */
            payeeName: string;
            /** @description Snapshot of the source date (RFC3339) */
            date: string;
            /** @description Snapshot of the source total outflow */
            totalOutflow: number;
            /** @description Snapshot of the source total inflow */
            totalInflow: number;
            /** @description Sum of the source expense-share lines (outflow) */
            requestedOutflow: number;
            /** @description Sum of the source expense-share lines (inflow) */
            requestedInflow: number;
            /** @description Snapshot of the source note */
            note: string;
            /** @description Every member's portion (open-edit by any member) */
            splits: components["schemas"]["shareSplit"][];
        };
        shareSplit: {
            /** @description The member budget this split belongs to */
            memberBudgetId: number;
            /** @description The member's outflow portion (0,0 means not participating) */
            splitOutflow: number;
            /** @description The member's inflow portion (0,0 means not participating) */
            splitInflow: number;
            /** @description Only the caller's own categorization lines, omitted for other members */
            lines: components["schemas"]["splitLine"][];
        };
        splitLine: {
            /** @description The split line id */
            id: number;
            /** @description The destination account id (present on transfer lines) */
            destAccountId?: number;
            /** @description The category id (present on spend lines) */
            categoryId?: number;
            /** @description The outflow of this line */
            outflow: number;
            /** @description The inflow of this line */
            inflow: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
