CREATE TABLE IF NOT EXISTS budget (
    id INTEGER PRIMARY KEY,
    name string NOT NULL
);

CREATE TABLE IF NOT EXISTS allocation (
    id INTEGER PRIMARY KEY,
    budget INTEGER NOT NULL REFERENCES budget (id) ON DELETE CASCADE,
    category INTEGER NOT NULL REFERENCES category (id) ON DELETE CASCADE,
    amount INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS account (
    id INTEGER PRIMARY KEY,
    budget INTEGER NOT NULL REFERENCES budget (id) ON DELETE CASCADE,
    name STRING NOT NULL
);

CREATE TABLE IF NOT EXISTS "transaction" (
    id INTEGER PRIMARY KEY,
    date DATETIME NOT NULL,
    account INTEGER NOT NULL REFERENCES account (id) ON DELETE CASCADE,
    payee INTEGER NOT NULL REFERENCES payee (id) ON DELETE CASCADE,
    total_outflow INTEGER NOT NULL DEFAULT 0,
    total_inflow INTEGER NOT NULL DEFAULT 0,
    reconciled BOOL NOT NULL DEFAULT false,
    note STRING NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS transaction_split (
    id INTEGER PRIMARY KEY,
    "transaction" INTEGER NOT NULL REFERENCES "transaction" (id) ON DELETE CASCADE,
    to_account INTEGER NOT NULL REFERENCES account (id) ON DELETE CASCADE,
    from_account INTEGER NOT NULL REFERENCES account (id) ON DELETE CASCADE,
    category INTEGER NOT NULL REFERENCES category (id) ON DELETE CASCADE,
    outflow INTEGER NOT NULL DEFAULT 0,
    inflow INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS payee (
    id INTEGER PRIMARY KEY,
    budget INTEGER NOT NULL REFERENCES budget (id) ON DELETE CASCADE,
    name STRING NOT NULL
);

CREATE TABLE IF NOT EXISTS payee_default_split (
    id INTEGER PRIMARY KEY,
    payee INTEGER NOT NULL REFERENCES payee (id) ON DELETE CASCADE,
    to_account INTEGER NOT NULL REFERENCES account (id) ON DELETE CASCADE,
    from_account INTEGER NOT NULL REFERENCES account (id) ON DELETE CASCADE,
    category INTEGER NOT NULL REFERENCES category (id) ON DELETE CASCADE,
    outflow INTEGER NOT NULL,
    inflow INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS category (
    id INTEGER PRIMARY KEY,
    budget INTEGER NOT NULL REFERENCES budget (id) ON DELETE CASCADE,
    name STRING NOT NULL
);

CREATE TABLE IF NOT EXISTS goal (
    id INTEGER PRIMARY KEY,
    budget INTEGER NOT NULL REFERENCES budget (id) ON DELETE CASCADE,
    name string NOT NULL, 
    type STRING NOT NULL,
    start DATETIME NOT NULL,
    end DATETIME,
    category INTEGER NOT NULL REFERENCES category (id) ON DELETE CASCADE,
    amount INTEGER NOT NULL
);
