// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package data

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO account (
  budget,
  name
) VALUES (
  ?,
  ?
)
RETURNING id, budget, name
`

type CreateAccountParams struct {
	Budget int64
	Name   interface{}
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount, arg.Budget, arg.Name)
	var i Account
	err := row.Scan(&i.ID, &i.Budget, &i.Name)
	return i, err
}
