// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: allocation.sql

package data

import (
	"context"
)

const createAllocation = `-- name: CreateAllocation :one
INSERT INTO allocation (
  budget,
  category,
  amount
) VALUES (
  ?,
  ?,
  ?
)
RETURNING id, budget, category, amount
`

type CreateAllocationParams struct {
	Budget   int64
	Category int64
	Amount   int64
}

func (q *Queries) CreateAllocation(ctx context.Context, arg CreateAllocationParams) (Allocation, error) {
	row := q.db.QueryRowContext(ctx, createAllocation, arg.Budget, arg.Category, arg.Amount)
	var i Allocation
	err := row.Scan(
		&i.ID,
		&i.Budget,
		&i.Category,
		&i.Amount,
	)
	return i, err
}
