// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: budget.sql

package data

import (
	"context"
)

const createBudget = `-- name: CreateBudget :one
INSERT INTO budget (
  name
) VALUES (
  ?
)
RETURNING id, name
`

func (q *Queries) CreateBudget(ctx context.Context, name interface{}) (Budget, error) {
	row := q.db.QueryRowContext(ctx, createBudget, name)
	var i Budget
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
