// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: category.sql

package data

import (
	"context"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO category (
  budget,
  name
) VALUES (
  ?,
  ?
)
RETURNING id, budget, name
`

type CreateCategoryParams struct {
	Budget int64
	Name   interface{}
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory, arg.Budget, arg.Name)
	var i Category
	err := row.Scan(&i.ID, &i.Budget, &i.Name)
	return i, err
}
