// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: goal.sql

package data

import (
	"context"
	"database/sql"
	"time"
)

const createGoal = `-- name: CreateGoal :one
INSERT INTO goal (
  budget,
  name,
  type,
  start,
  end,
  category,
  amount
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
RETURNING id, budget, name, type, start, "end", category, amount
`

type CreateGoalParams struct {
	Budget   int64
	Name     interface{}
	Type     interface{}
	Start    time.Time
	End      sql.NullTime
	Category int64
	Amount   int64
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error) {
	row := q.db.QueryRowContext(ctx, createGoal,
		arg.Budget,
		arg.Name,
		arg.Type,
		arg.Start,
		arg.End,
		arg.Category,
		arg.Amount,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.Budget,
		&i.Name,
		&i.Type,
		&i.Start,
		&i.End,
		&i.Category,
		&i.Amount,
	)
	return i, err
}
