// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package data

import (
	"database/sql"
	"time"
)

type Account struct {
	ID     int64
	Budget int64
	Name   interface{}
}

type Allocation struct {
	ID       int64
	Budget   int64
	Category int64
	Amount   int64
}

type Budget struct {
	ID   int64
	Name interface{}
}

type Category struct {
	ID     int64
	Budget int64
	Name   interface{}
}

type Goal struct {
	ID       int64
	Budget   int64
	Name     interface{}
	Type     interface{}
	Start    time.Time
	End      sql.NullTime
	Category int64
	Amount   int64
}

type Payee struct {
	ID     int64
	Budget int64
	Name   interface{}
}

type PayeeDefaultSplit struct {
	ID          int64
	ToAccount   int64
	FromAccount int64
	Category    int64
	Outflow     int64
	Inflow      int64
}

type Transaction struct {
	ID         int64
	Date       time.Time
	Account    int64
	Payee      int64
	Reconciled bool
	Note       interface{}
}

type TransactionSplit struct {
	ID          int64
	Transaction int64
	ToAccount   int64
	FromAccount int64
	Category    int64
	Outflow     int64
	Inflow      int64
}
