// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payee.sql

package data

import (
	"context"
)

const createPayee = `-- name: CreatePayee :one
INSERT INTO payee (
  budget,
  name
) VALUES (
  ?,
  ?
)
RETURNING id, budget, name
`

type CreatePayeeParams struct {
	Budget int64
	Name   interface{}
}

func (q *Queries) CreatePayee(ctx context.Context, arg CreatePayeeParams) (Payee, error) {
	row := q.db.QueryRowContext(ctx, createPayee, arg.Budget, arg.Name)
	var i Payee
	err := row.Scan(&i.ID, &i.Budget, &i.Name)
	return i, err
}
