// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payee_default_split.sql

package data

import (
	"context"
)

const createPayeeDefaultSplit = `-- name: CreatePayeeDefaultSplit :one
INSERT INTO payee_default_split (
  payee,
  to_account,
  from_account,
  category,
  outflow,
  inflow
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
RETURNING id, payee, to_account, from_account, category, outflow, inflow
`

type CreatePayeeDefaultSplitParams struct {
	Payee       int64
	ToAccount   int64
	FromAccount int64
	Category    int64
	Outflow     int64
	Inflow      int64
}

func (q *Queries) CreatePayeeDefaultSplit(ctx context.Context, arg CreatePayeeDefaultSplitParams) (PayeeDefaultSplit, error) {
	row := q.db.QueryRowContext(ctx, createPayeeDefaultSplit,
		arg.Payee,
		arg.ToAccount,
		arg.FromAccount,
		arg.Category,
		arg.Outflow,
		arg.Inflow,
	)
	var i PayeeDefaultSplit
	err := row.Scan(
		&i.ID,
		&i.Payee,
		&i.ToAccount,
		&i.FromAccount,
		&i.Category,
		&i.Outflow,
		&i.Inflow,
	)
	return i, err
}
