// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transaction.sql

package data

import (
	"context"
	"time"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transaction (
  date,
  account,
  payee,
  total_outflow,
  total_inflow,
  reconciled,
  note
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
RETURNING id, date, account, payee, total_outflow, total_inflow, reconciled, note
`

type CreateTransactionParams struct {
	Date         time.Time
	Account      int64
	Payee        int64
	TotalOutflow int64
	TotalInflow  int64
	Reconciled   bool
	Note         interface{}
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.Date,
		arg.Account,
		arg.Payee,
		arg.TotalOutflow,
		arg.TotalInflow,
		arg.Reconciled,
		arg.Note,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Account,
		&i.Payee,
		&i.TotalOutflow,
		&i.TotalInflow,
		&i.Reconciled,
		&i.Note,
	)
	return i, err
}
