// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transaction_split.sql

package data

import (
	"context"
)

const createTransactionSplit = `-- name: CreateTransactionSplit :one
INSERT INTO transaction_split (
  "transaction",
  to_account,
  from_account,
  category,
  outflow,
  inflow
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
RETURNING id, "transaction", to_account, from_account, category, outflow, inflow
`

type CreateTransactionSplitParams struct {
	Transaction int64
	ToAccount   int64
	FromAccount int64
	Category    int64
	Outflow     int64
	Inflow      int64
}

func (q *Queries) CreateTransactionSplit(ctx context.Context, arg CreateTransactionSplitParams) (TransactionSplit, error) {
	row := q.db.QueryRowContext(ctx, createTransactionSplit,
		arg.Transaction,
		arg.ToAccount,
		arg.FromAccount,
		arg.Category,
		arg.Outflow,
		arg.Inflow,
	)
	var i TransactionSplit
	err := row.Scan(
		&i.ID,
		&i.Transaction,
		&i.ToAccount,
		&i.FromAccount,
		&i.Category,
		&i.Outflow,
		&i.Inflow,
	)
	return i, err
}
