// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transaction.sql

package data

import (
	"context"
	"time"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO "transaction" (
  date,
  account,
  payee,
  total_outflow,
  total_inflow,
  reconciled,
  note
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
RETURNING id, date, account, payee, total_outflow, total_inflow, reconciled, note
`

type CreateTransactionParams struct {
	Date         time.Time
	Account      int64
	Payee        int64
	TotalOutflow int64
	TotalInflow  int64
	Reconciled   bool
	Note         interface{}
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.Date,
		arg.Account,
		arg.Payee,
		arg.TotalOutflow,
		arg.TotalInflow,
		arg.Reconciled,
		arg.Note,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Account,
		&i.Payee,
		&i.TotalOutflow,
		&i.TotalInflow,
		&i.Reconciled,
		&i.Note,
	)
	return i, err
}

const listAccountTransactions = `-- name: ListAccountTransactions :many
SELECT
  t.id,
  t.date,
  p.name AS payee_name,
  t.reconciled,
  t.note,
  ts.id AS split_id,
  ts.to_account,
  ato.name AS to_account_name,
  ts.from_account,
  afrom.name AS from_account_name,
  ts.category,
  c.name AS category_name,
  ts.outflow,
  ts.inflow
FROM "transaction" AS t
JOIN payee AS p ON p.id = t.payee
JOIN transaction_split AS ts ON ts."transaction" = t.id
LEFT JOIN account AS ato ON ato.id = ts.to_account
LEFT JOIN account AS afrom ON afrom.id = ts.from_account
LEFT JOIN category AS c ON c.id = ts.category
WHERE t.account = ?
ORDER BY t.date ASC, t.id ASC, ts.id ASC
`

type ListAccountTransactionsRow struct {
	ID              int64
	Date            time.Time
	PayeeName       interface{}
	Reconciled      bool
	Note            interface{}
	SplitID         int64
	ToAccount       int64
	ToAccountName   interface{}
	FromAccount     int64
	FromAccountName interface{}
	Category        int64
	CategoryName    interface{}
	Outflow         int64
	Inflow          int64
}

func (q *Queries) ListAccountTransactions(ctx context.Context, account int64) ([]ListAccountTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAccountTransactions, account)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountTransactionsRow
	for rows.Next() {
		var i ListAccountTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.PayeeName,
			&i.Reconciled,
			&i.Note,
			&i.SplitID,
			&i.ToAccount,
			&i.ToAccountName,
			&i.FromAccount,
			&i.FromAccountName,
			&i.Category,
			&i.CategoryName,
			&i.Outflow,
			&i.Inflow,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
